# Generated by Django 5.2.1 on 2025-06-09 18:59

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-end_date'], 'verbose_name': 'Ціль', 'verbose_name_plural': 'Цілі'},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.AddField(
            model_name='goal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Поточна сума'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Виконана'), ('failed', 'Провалена')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цільова сума'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва цілі'),
        ),
    ]
