# Generated by Django 5.2.1 on 2025-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_goal_options_remove_goal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис цілі'),
        ),
    ]
